version: 3.1
services:
    www:
        container_name: www_container
        build: 
            context: .
            dockerfile: Dockerfile
            ports:
                - 80:80
            volumes: 
                - ./app/public:/var/www/html
                - ./app:/var/www/
            environment:
                - APP_NAME=Laravel
                - APP_ENV=local
                - APP_KEY=base64:vNWHSHdpGSQ4ylaG81ONT/YKqLpi8EpHm/2Ri8148ac=
                - APP_DEBUG=true
                - DB_CONNECTION=mysql
                - DB_HOST=mysql_db
                - DB_PORT=3306
                - DB_DATABASE=imoveis
                - DB_USERNAME=root
                - DB_PASSWORD=senha